server:
  port: 8081

spring:
  application:
    name: service-stock
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/alzheimer_stock
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

info:
  app:
    name: Service Stock - Gestion de Stock
    description: Microservice de gestion de stock (Catégories, Produits, Commandes, Panier)
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

app:
  upload:
    dir: uploads

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
